#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

$loader = new \Nette\Loaders\RobotLoader;

$loader->addDirectory(__DIR__);
$loader->setCacheStorage(new \Nette\Caching\Storages\FileStorage('temp'));

$loader->register();

PHPUnit_TextUI_Command::main();