#!/usr/bin/env php
<?php
/**
 * Settings directories
 */
// cache for RobotLoader, if not exists, make automatically in vendor/developerhub/php-testcase
define('TEMP_DIR', __DIR__. '/temp');
// PHPUnit tests
define('TESTS_DIR', __DIR__ . '/../../../tests');
// directory with the application
define('APP_DIR', __DIR__ . '/../../../app');
// file for composer autoload
define('COMPOSER_AUTOLOAD', __DIR__ . '/../../autoload.php');

var_dump(realpath(COMPOSER_AUTOLOAD));
if (realpath(COMPOSER_AUTOLOAD) === false) {
	die;
}

if (realpath(TEMP_DIR) === false) {
	mkdir(TEMP_DIR);
}

if (realpath(TESTS_DIR) === false) {
	die(
		'The tests are expected in the directory: ' . TESTS_DIR . PHP_EOL .
		'If are in a different directory, set the path to him in constant TESTS_DIR in the file runTests.' . PHP_EOL
	);
}

if (realpath(APP_DIR) === false) {
	die(
		'The application are expected in the directory: ' . APP_DIR . PHP_EOL .
		'If are in a different directory, set the path to him in constant APP_DIR in the file runTests.' . PHP_EOL
	);
}


require COMPOSER_AUTOLOAD;

$loader = new \Nette\Loaders\RobotLoader;
$loader->addDirectory(TESTS_DIR);
$loader->addDirectory(APP_DIR);
$loader->setCacheStorage(new \Nette\Caching\Storages\FileStorage(TEMP_DIR));
$loader->register();

PHPUnit_TextUI_Command::main();